language: node_js
node_js:
  - "5.7.1"

addons:
  firefox: "44.0"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm run typings

script:
  - npm run lint
  - npm test
